### ISSUE TITLE
Add a magic number to detect if the "EEPROM" is correctly populated

### ISSUE THREAD

**Issue by j-marjanovic** [MicroTCA-Tech-Lab/mmc-mailbox#1]
If the memory layout is not yet completely finalized, it would be nice to have at least a couple of bytes of magic numbers to be able to detect that the I2C "EEPROM" is in fact working and populated with the relevant data.

Imagine a scenario where the u-boot wants to read the unique ID but the MMC was not yet updated to a version with the mailbox. Having a couple of magic bytes will help us distinguish between the "legacy implementation" and the new one on our Kowalski AMC.

**Comment by patrislav1** [comment]
Thanks for the suggestion! Fixed in a82a74182bf3afee024657cb1d510eadca66d48e
